<?php namespace Anekdotes\Manager;

use Closure; use Input; use File; use Imagine\Image\ImageInterface; use Imagine\Image\Box; use Sitebase\Image\Image;

class Manager {

  protected static $exts = array('jpg', 'png', 'jpeg');
  protected static $path = 'uploads/';
  protected static $weight = 3000000;
  protected static $size = null;
  protected static $prefix = 'public/';
  public static $errors = array();
  public static $empty = false;
  public $success = false;

  public function __construct($options = array()) {
    if (isset($options['exts']))
     self::$exts = $options['exts'];
    if (isset($options['path']))
     self::$path = $options['path'];
    if (isset($options['weight']))
     self::$weight = $options['weight'];
    if (isset($options['size']))
     self::$size = $options['size'];
    if (isset($options['prefix']))
     self::$prefix = $options['prefix'];
  }

  public function manage($file, Closure $uploadCallback = null) {
    ini_set('memory_limit', '-1');
    $fileInfo = Input::getFile($file);
    if (is_null($fileInfo['error']) || $fileInfo['error'] > 0){
      self::$empty = true;
      return false;
    }
    $fileInfo = array_merge($fileInfo, pathinfo($fileInfo['name']));
    $ext = strtolower($fileInfo['extension']);
    $tmpPath = $fileInfo['tmp_name'];

    //basic validation
    if ($fileInfo['size'] / 1000000 > self::$weight){
      self::error('The file is too big');
      return false;
    }
    if (!in_array($ext, self::$exts)){
      self::error('The file extension is not supported');
      return false;
    }

    $filename = date('YmdHis', time());
    $quality = 70;
    //there's a callback, execute the callback and return its value as new filename
    if ($uploadCallback){
      $filename = $uploadCallback();
    }
    $newPath = APP_ROOT . self::$prefix . self::$path . $filename;

    if (self::$size && is_array(self::$size)) {
      foreach (self::$size as $size => $config) {
        $newPath = self::$path . $size . '/';
        self::directorize($newPath);
        $newPath = APP_ROOT . self::$prefix . $newPath . $filename;
        $quality = isset($config['quality']) ? $config['quality'] : 75;
        self::upload($tmpPath, $newPath, $ext, $quality, function($picture) use ($config) {
          $size = $picture->getSize();
          switch ($config['resize']) {
            case 'widen':
              $picture = $picture->resize($size->widen($config['width']));
              break;
            case 'heighten':
              $picture = $picture->resize($size->heighten($config['height']));
              break;
            case 'max':
              if ($size->getWidth() > $config['width']) {
                $picture = $picture->resize($size->widen($config['width']));
              }
              if ($size->getHeight() > $config['height']) {
                $picture = $picture->resize($size->heighten($config['height']));
              }
              break;
          }
          if ($config['crop']) {
            $size = new Box($config['width'], $config['height']);
            $mode = ImageInterface::THUMBNAIL_OUTBOUND;
            $picture = $picture->thumbnail($size, $mode);
          }
          return $picture;
        });
      };
      $this->success = true;
      return true;
    }
    self::upload($tmpPath, $newPath, $ext, $quality);
    $this->success = true;
    return true;
  }

  public function fromUrl($url, $destination, $newFileName, Closure $uploadCallback = null){
    if ($imageContent = @file_get_contents($url)){
      self::directorize($destination);
      file_put_contents(self::$prefix . $newFileName, $imageContent);
    }
  }

  public function upload($tmpPath, $newPath, $ext, $quality, Closure $imageCallback = null) {
    if ($imageCallback) {
      $file = Image::open($tmpPath);
      $file = $imageCallback($file);
      $tmpPath = $tmpPath . '.' . $ext;
      $file->save($tmpPath, array('quality' => $quality));
    }
    $tehfile = new File();
    $tehfile->move($tmpPath, $newPath);
  }

  public function error($message = ''){
    self::$errors[] = $message;
  }

  public function directorize($path){
    $file = new File;
    $folders = explode('/', $path);
    $pathbuild = APP_ROOT . self::$prefix;
    foreach ($folders as $folder) {
      $pathbuild .= "{$folder}/";
      $cond = $file->exists($pathbuild) && $file->isDirectory($pathbuild);
      if (! $cond){
        $file->makeDirectory($pathbuild);
        $file->put("{$pathbuild}.gitkeep", "Generated by Manager.php");
      }
    }
  }
}
